repos:
  -
    repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        files: ^(chatushka|tests)/.+\.py$
      - id: black
        name: black
        entry: black
        language: system
        files: ^(chatushka|tests)/.+\.py$
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        files: ^(chatushka|tests)/.+\.py$
#      - id: mypy
#        name: mypy
#        entry: mypy
#        language: system
#        files: ^(chatushka|tests)/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
