---
kind: 'regex'
args:
  rule: '^(.*\s)*hello\s*.*$'
action:
  kind: 'message'
  args:
    template: 'hi'
---
kind: 'command'
args:
  token: 'ping'
action:
  kind: 'message'
  args:
    template: 'pong {{ arg.0 }}'
---
kind: 'command'
args:
  token: 'id'
action:
  kind: 'rhai'
  args:
    script: '"chat_id: " + to_string(CHAT_ID)'
