---
kind: 'regex'
args:
  rule: '^(.*\s)*hello\s*.*$'
action:
  kind: 'message'
  args:
    template: 'hie'
---
kind: 'command'
args:
  token: 'ping'
action:
  kind: 'message'
  args:
    template: 'pong'
