---
kind: 'regex'
args:
  rule: '^(.*\s)*hello\s*.*$'
action:
  kind: 'message'
  args:
    template: 'hi'
---
kind: 'command'
args:
  token: 'ping'
action:
  kind: 'message'
  args:
    template: 'pong {{ arg.0 }}'
---
kind: 'command'
args:
  token: 'foo'
action:
  kind: 'rhai'
  args:
    entrypoint: 'matcher_cb'
    script: |
      fn matcher_cb(chat_id, replay_id, message) {
          send_message("test foo bar")
      }
