---
- kind: 'regex'
  rule: '^(.*\s)*hello\s*.*$'
  actions:
    kind: 'message'
    template: 'hi'
- kind: 'command'
  token: 'health'
  case_insensitive: true
  prefix: '!'
  actions:
    kind: 'message'
    template: 'bar'
