[tool.poetry]
name = "chatushka"
version = "0.7.1"
description = "Bot that can make your chat explode!"
authors = ["Aleksandr Shpak <shpaker@gmail.com>"]
readme = "readme.md"
homepage = "https://github.com/shpaker/chatushka"
repository = "https://github.com/shpaker/chatushka"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
httpx = "^0.22.0"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
aiocron = "^1.6"
motor = "^2.5.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
isort = "^5.9.2"
black = "^22.1.0"
flake8 = "^4.0.1"
pylint = "^2.9.3"
mypy = "^0.931"
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
verbose = 1
color = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
src_paths = ["chatushka", "tests"]
skip = [".mypy_cache", ".pytest_cache", "venv"]

[tool.pylint.messages_control]
disable = "missing-docstring,logging-fstring-interpolation,too-few-public-methods,too-many-arguments,duplicate-code"
extend-ignore = "E203,W503"

[tool.pylint.format]
max-line-length = "120"
indent-string = "    "
good-names = "db, i, x, y, T, fh"

[tool.pylint.master]
ignore = "venv,tests"
indent-string = "    "
extension-pkg-whitelist = "pydantic"
