fn_args_layout = "Vertical"
force_multiline_blocks = true
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
max_width = 87
newline_style = "Unix"
reorder_imports = true
tab_spaces = 4
trailing_comma = "Always"
