---
name: Build

on:
  push:
    tags:
      - '*'

env:
  POETRY_VERSION: "1.4.0"

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      - shell: bash
        run: |
          export VERSION_PY_PATH=$(basename ${GITHUB_REPOSITORY})/__version__.py
          export REPO_URL=${GITHUB_SERVER_URL}/${{ github.repository }}
          sed -i 's,0.0.0,${{ steps.extract_name_and_version.outputs.ver }},g' pyproject.toml
          sed -i 's,0.0.0,${{ steps.extract_name_and_version.outputs.ver }},g' ${VERSION_PY_PATH}
      - run: |
          python -m pip install poetry==${POETRY_VERSION}
      - run: poetry build
      - run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASS }}
          poetry publish

  docker:
    runs-on: ubuntu-latest
    needs:
      - pypi
    env:
      REGISTRY_HOST: ghcr.io
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      - shell: bash
        run: |
          export VERSION_PY_PATH=$(basename ${GITHUB_REPOSITORY})/__version__.py
          export REPO_URL=${GITHUB_SERVER_URL}/${{ github.repository }}
          sed -i 's,0.0.0,${{ steps.extract_name_and_version.outputs.ver }},g' pyproject.toml
          sed -i 's,0.0.0,${{ steps.extract_name_and_version.outputs.ver }},g' ${VERSION_PY_PATH}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: chatushka_version=${{ steps.extract_name_and_version.outputs.ver }}
          tags: |
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:latest"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.sha }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.major_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
          labels:
            "org.opencontainers.image.source=${GITHUB_SERVER_URL}/${{ github.repository }}"
          cache-from: type=registry,ref=${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}
          cache-to: type=inline
