name: Build

on:
  push:
    tags:
      - '*'

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      -
        name: Set package meta-data
        shell: bash
        run: |
          sed -i 's/$__VERSION__/${{ steps.extract_name_and_version.outputs.ver }}/g' pyproject.toml
          sed -i 's/$__URL__/${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/g' pyproject.toml
          sed -i 's/$__VERSION__/${{ steps.extract_name_and_version.outputs.ver }}/g' $(basename ${GITHUB_REPOSITORY})/__version__.py
          sed -i 's/$__URL__/${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/g' $(basename ${GITHUB_REPOSITORY})/__version__.py
          cat $(basename ${GITHUB_REPOSITORY})/__version__
      -
        name: Dependencies
        run: |
          python -m pip install poetry==1.1.7
      -
        name: Build
        run: poetry build
      -
        name: Publish
        run: |
          sed -i 's/__NAME__/'${CI_PROJECT_TITLE}'/g' ${HELM_CHART_PATH}
          poetry config http-basic.pypi ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASS }}
          poetry publish

  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY_HOST: ghcr.io
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=name;]$(echo ${GITHUB_REPOSITORY#*/})"
          echo "##[set-output name=ver;]$(echo ${GITHUB_REF#refs/*/})"
          echo "##[set-output name=minor_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*})"
          echo "##[set-output name=major_ver;]$(TMP_VAR=${GITHUB_REF#refs/*/}; echo ${TMP_VAR%.*.*})"
          echo "##[set-output name=sha;]$(git rev-parse --short "$GITHUB_SHA")"
        id: extract_name_and_version
      -
        name: Set package meta-data
        shell: bash
        run: |
          sed -i 's/$__VERSION__/'${{ steps.extract_name_and_version.outputs.ver }}'/g' pyproject.toml
          sed -i 's/$__URL__/'${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}'/g' pyproject.toml
          sed -i 's/$__VERSION__/'${{ steps.extract_name_and_version.outputs.ver }}'/g' $(basename ${GITHUB_REPOSITORY})/__version__.py
          sed -i 's/$__URL__/'${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}'/g' $(basename ${GITHUB_REPOSITORY})/__version__.py
          cat $(basename ${GITHUB_REPOSITORY})/__version__
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ${{ env.REGISTRY_HOST }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:latest"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.sha }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.major_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}"
            "${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.ver }}"
          labels:
            "org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          build-args: |
            SHORTENER_VERSION=${{ steps.extract_name_and_version.outputs.ver }}
          cache-from: type=registry,ref=${{ env.REGISTRY_HOST }}/${{ github.repository }}:${{ steps.extract_name_and_version.outputs.minor_ver }}
          cache-to: type=inline
