---
name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: sources
    steps:
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: |
          python -m pip install poetry==1.1.7
          poetry install
      -
        name: pytest
        run: poetry run pytest -vv
