---
name: Testing

on:
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.1.13"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        uses: actions/checkout@v2
      -
        name: Set package meta-data
        shell: bash
        run: |
          export VERSION_PY_PATH=$(basename ${GITHUB_REPOSITORY})/__version__.py
          sed -i 's,$__VERSION__,${{ steps.extract_name_and_version.outputs.ver }},g' ${VERSION_PY_PATH}
      -
        name: dependencies
        run: |
          python -m pip install poetry==${POETRY_VERSION}
          poetry install
      -
        name: install hooks
        run: poetry run pre-commit install-hooks
      -
        name: flake8
        run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure
      -
        name: pylint
        run: poetry run pre-commit run pylint --all-files --show-diff-on-failure
#      -
#        name: mypy
#        run: poetry run pre-commit run mypy --all-files --show-diff-on-failure

#  tests:
#    runs-on: ubuntu-latest
#    env:
#      SOURCES_DIR: sources
#    steps:
#      -
#        name: Set up Python 3.9
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.9"
#      -
#        uses: actions/checkout@v2
#      -
#        name: Install dependencies
#        run: |
#          python -m pip install poetry==1.1.7
#          poetry install
#      -
#        name: pytest
#        run: poetry run pytest -vv
