---
name: Testing

on:
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.1.13"

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pre-commit-hook:
          - isort
          - black
          - flake8
          - pylint
#          - mypy
    steps:
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        uses: actions/checkout@v2
      -
        name: Set package meta-data
        shell: bash
        run: sed -i 's,$__VERSION__,0.0.0,g' pyproject.toml
      -
        name: dependencies
        run: |
          python -m pip install poetry==${POETRY_VERSION}
          poetry install
      -
        name: install hooks
        run: poetry run pre-commit install-hooks
      -
        name: ${{ matrix.pre-commit-hook }}
        run: poetry run pre-commit run ${{ matrix.pre-commit-hook }} --all-files --show-diff-on-failure

#  tests:
#    runs-on: ubuntu-latest
#    env:
#      SOURCES_DIR: sources
#    steps:
#      -
#        name: Set up Python 3.9
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.9"
#      -
#        uses: actions/checkout@v2
#      -
#        name: Install dependencies
#        run: |
#          python -m pip install poetry==1.1.7
#          poetry install
#      -
#        name: pytest
#        run: poetry run pytest -vv
