---
name: Tests

on:
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.4.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        JUST_COMMAND:
          - linters
          - tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - run: python -m pip install poetry==${POETRY_VERSION}
      - run: poetry install -vvv --no-root --only=main,${{ matrix.JUST_COMMAND }}
      - run: just ${{ matrix.JUST_COMMAND }}
