---
name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOURCES_DIR: chatushka
    strategy:
      matrix:
        just-trigger:
          - "lint"
          - "tests"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v3
      - run: python -m pip install poetry~=1.8.0
      - run: poetry install --no-root
      - run: just ${{ matrix.just-trigger }}
